#import "@local/superTemplate:0.1.3": *

#import math_mod: *
#show: notes.with("Coxeter Groups Notes", "Nate Annau")

= Introduction

== Geometric Reflection Groups

#notation([
  - The unit sphere is $SS^n$
  - Euclidean space is $EE^n$
  - Hyberbolic space is $HH^n$

  In general we denote these by $XX^n$.
])

#defn([Riemannian Manifold], [
  A geometric space on which notions like distance, angles, length, volume, and curvature are defined.

  Formally, let $M$ be a smooth manifold.
  For each point $p in M$, there is an associated space $T_p M$ called the tangent space of $M$ at $p$ (can be thought of as vectors tangent to $M$ at $p$.)
  However, we don't automatically have an inner product if we do this, so we put a Riemannian metric $g$ on $M$, which is a positive definite inner product $ g_p : T_p M times T_p M -> RR $ such that there is some smoothness property.
  A smooth manifold together with a Riemannian metric $g$ is a Riemannian manifold $(M, g)$.
])

#defn([Sectional Curvature], [
  Given a Riemannian manifold and linearly independent tangent vectors at the same point $u$ and $v$, define
  $
    K (u, v) = ip(R(u, v)v, u) / (ip(u, u) ip(v, v) - ip(u, v)^2)
  $
  where $R$ is the Riemann curvature tensor.
])

#defn([Totally Geodesic Submanifold], [
  A submanifold $M$ of a Riemannian manifold $(overline(M), overline(g))$ is called *totally geodesic* if any geodesic on the submanifold $M$ with its induced Riemannian metric $g$ is also a geodesic on the Riemannian manifold $(overline(M), overline(g))$.
])

#defn([Codimension], [
  If $M$ is a submanifold of a Riemannian manifold $overline(M)$, then the codimension is the different between dimensions:
  $
    codim (M) = dim (M) - dim (overline(M)).
  $
])

#defn([Connected Components], [
  The maximal connected subsets of a nonempty topological space are called the *connected components* of that space.
])

#example([], [
  $SS^n, EE^n$ and $HH^n$ are Riemannian manifolds, distinguished by their constant sectional curvatures of 1, 0, and -1 respectively.
  These spaces are notable as the only symmetric spaces to have totally geodesic codimension 1 submanifolds (called *hyperplanes*).
  Any hyperplane $cal(H) subset XX^n$ separates $XX^n$ into two connected components (*open half-spaces*).
  The union of a hyperplane $cal(H)$ with one of the open half spaces determining it is called a *closed half space*.

  Associated to each hyperplane $cal(H) subset XX^n$ there is an isometric reflection which fixes $cal(H)$ pointwise and exchanges the two half-spaces.
])

#defn([Tesselation], [
  The tiling of a surface with no overlaps and no gaps.
])

#example([Finite Dihedral Groups], [
  Consider $SS^1$ centered at the origin with two lines $ell_1$ and $ell_2$ meeting at a dihedral angle $pi / m$ for some $m >= 2$.

  For $i = 1, 2$ let $s_i$ be the isometric reflection about $ell_i$.
  Then the composition of reflections $s_1 s_2$ is rotation by $(2pi) / m$ about the origin, so $gen(s_1 s_2) iso C_m$ (the cyclic group of order $m$).

  The group $W = gen(s_1\, s_2)$ generated by $s_1$ and $s_2$ is the dihedral group of order $2m$, denoted by
  $
    W = D_(2 m) = gen(s_1\, s_2 | s_1^2 = s_2^2 = (s_1 s_2)^m = 1).
  $
  #note([
    Note that this is equivalent to the standard definiton of dihedral groups
    $
      D_(2n) &= gen(r\, s | r^n = s^2 = 1\, s r inv(s) = inv(r)) \
      &= gen(r\, s | r^n = s^2 = (s r)^2 = 1)
    $
    with $t = s r$.
  ])

  We think of $W = D_(2 m)$ as acting on $SS^1$.
  This induces a tessellation of $SS^1$ by $2m$ closed intervals which are in bijection with the elements of $W$.

  We can also think of $W$ as acting on $EE^2$, inducing a tessellation of the plane by $2m$ unbounded sectors.

  Another point of view is to see $W$ as the isometry group of a regular Euclidean $m$-gon embedded in the Euclidean plane, with a start vertex $v$ on line $ell_1$ and the midpoint of a line containing $v$ on $ell_2$.
  Then by taking the barycentric subdivision of the embedding of the polygon and projecting it to the sphere, we get the same result.
])

#example([Infinite Dihedral Group], [
  Consider the real line $EE^1$.
  Let $s_1$ and $s_2$ be reflections of the line over the points 0 and 1 respectively.
  Notice $s_1 s_2$ is a translation by 2 units to the left, so $gen(s_1 s_2) iso ZZ$ is infinite cyclic.

  This group is called the infinite dihedral group and has presenttation
  $
    W = D_infty = gen(s_1\, s_2 | s_1^2 = s_2^2)
  $
  Notationally, we can say $(s_i s_j)^infty = 1$ means the product $s_i s_j$ has finite order, so we can put the condition $(s_1 s_2)^infty = 1$ as well.

  The action of this group on $EE^1$ induces a tesselation of the line by closed intervals which are in bijection with the elements of $W$.
])

#defn([Simplex], [
  A generalization of the notion of a triangle or tetrahedron to arbitrary dimensions.
  In particular, it is a  $k$ dimensional polytope that is the convex hull of its $k + 1$ vertices.
])

#defn([Polytope and Link], [
  A *convex polytope* $P = P subset.eq XX^n$ is a convex, compact intersection of a finite number of closed half spaces in $XX^n$, with nonempty interior.

  The *link* of a vertex $v$ of $P$, denoted $link(v)$, is the $(n - 1)$ dimensional spherical polytope obtained by intersecting $P$ with a small sphere centered at $v$.

  A convex polytope $P$ is called *simple* if, for every vertex $v$ of $P$, $link(v)$ is a simplex.
])

#thm([], [
  Let $P = P^n$ be a simple convex polytop in $XX^n$, where $n >= 2$.
  Let ${F_i}_(i in I)$ be the collection of codimension-1 faces of $P^n$, with each face $F_i$ supported by the hyperplane $cal(H)_i$.

  Suppose that $forall i != j, F_i sect F_j != emptyset ==>$ the dihedral angle between $F_i$ and $F_j$ is $pi / (m_(i j)) fs m_(i j) >= 2$.

  For each $i in I$, let $s_i$ be the isometric reflection of $XX^n$ across the hyperplane $cal(H)_i$.
  Let $W$ be the group generated by the set of reflections ${s_i}_(i in I)$.
  Then
  1. The group has presentation $ W = gen(s_i | (s_i s_j)^(m_(i j)) = 1 forall i\, j in I) $
  2. The group $W$ is a discrete subgroup of $Isom(XX^n)$
  3. The convex polytope $P$ is a strict fundamental domain for the action of $W$ on $XX^n$, and the action of $W$ induces a tessellation of $XX^n$ by copies of $P$
], [
  To be discussed later.
])

== Coxeter Groups

#defn([Coxeter Group], [
  Let $I$ be a finite indexing set and let $S = {s_i}_(i in I)$.
  Let $M = (m_(i j)_(i, j in I)$ be a matrix such that
  - $m_(i i) = 1 forall i in I$
  - $m_(i j) = m_(j i) forall i, j in I$
  - $m_(i j) in {2, 3, 4, dots} union {infty}$ for all distinct $i, j in I$

  Then $M$ is called a _Coxeter matrix_.
  The associated _Coxeter group_ $W = W_M$ is defined by the presentation $ W = gen(S | (s_i s_j)^(m_(i j)) = 1 forall i\, j in I) $ or equivalently, $ W = gen(S | s_i^2 = 1 forall i in I "and" (s_i s_j)^(m_(i j)) = 1 forall "distinct" i\, j in I) $

  The pair $(W, S)$ is a _Coxeter system_ and the set $S$ is a _Coxeter generating set_ for $W$.
])

#remark([
  1. Notice that each $s_i$ has order 2 and each $s_i s_j$ has order $m_(i j)$.

  2. The presentations for dihedral groups together with Theorem imply that all geometric reflection groups are Coxeter groups.
])
