#import "@local/superTemplate:0.3.0": *
#import "@local/superTheorems:0.1.0": *
#import math_mod: *
#show: notes.with("Notes on Geometric and Topological Aspects of Coxeter Groups and Buildings", "Jesse Cobb")

= Coxeter Group

== Geometric Reflection Groups

#rem[
  $SS^n$ denotes the $n$-dimensional unit sphere, $EE^n$ denotes the $n$-dimensional Euclidean space, and $HH^n$ denotes the $n$-dimensional Hyperbolic space.

  $XX^n$ denotes any of the previously mentioned $n$-dimensional spaces.
]

#ex(name: [Finite Dihedral Group])[
  Given two reflections, $s_1$ and $s_2$, offset by an angle of $pi/m$ across the lines $l_1$ and $l_2$ respectively, we find $
    D_(2 m)
      &= ang(s_1, s_2 | s_1^2 = s_2^2 = (s_1 s_2)^m = 1)
  $ such that $s_1 s_2$ is a rotation by $(2 pi)/m$. This induces a tessellation on $SS^1$ by $2m$ closed intervals, $EE^1$ by $2 m$ unbounded sectors, or on the unit disc with $2 m$ bounded sectors. $D_(2 m)$ can also be seen as the isometry group of a regular $m$-gon with a vertex $v$ being on the intersection of $l_1$ with $SS^1$ and an edge drawn from $v$ bisected by $l_2$.

  By letting $s = s_1$ and $r = s_1 s_2$ we get the standard presentation $
    D_(2 m)
      &= ang(s, r | r^m = s^2 = 1, r s = s r^(-1)).
  $
]

#ex(name: [Infinite Dihedral Group])[
  Let $s_1$ and $s_2$ be the reflection of $EE^1$ (real line) over $0$ and $1$ respectively. Note that $s_1 s_2$ is a translation by $2$ units. Note that $
    D_infty
      = ang(s_1, s_2 | s_1^2 = s_2^2 = (s_1 s_2)^infty = 1)
  $ is the infinite dihedral group. Note this can also be thought of like a finite dihedral group with the angle between the reflections to be approaching zero such that the reflections are parallel.
]

#defn(name: [Polytopes and links])[
  A convex polytope $P = P^n subset.eq XX^n$ is a convex compact intersection of a finite number of closed half-spaces in $XX^n$, with nonempty interior. A linke of a vertex $v$, $"link"(v)$, is the $(n - 1)$-dimensional spherical polytope obtained from the intersection of $P$ with a small sphere around $v$. A convex polytope $P$ is simple if, for every vertex $v$ of $P$, $"link"(v)$ is a simplex.

  #ex(name: [Convex polygon])[
    If $n = 2$ then for a convex polytope $P subset.eq XX^2$ a link $"link"(v)$ is a closed interval in $SS^1$ (a spherical $1$-simplex) equal to the interior angle at $v$.
  ]
]

#defn(name: [Fundamental Domain])[
  Let $G$ act on a topological space $X$ by homeomorphisms. A fundamental domain is a closed, connected subset $C$ of $X$ such that $G x sect C eq.not emptyset$ for all $x in X$ and $G x sect C = {x}$ for $x$ in the interior of $C$. $C$ is a strict fundamental domain if $G x sect C = {x}$ for every $x in C$, in other words $C$ contains exactly one point from each $G$-orbit.

  #ex(name: [Fundamental Domain of $D_infty$])[
    Note $[0, 1]$ is a strict fundamental domain for the action of $D_infty$ on $EE^1$.
  ]
]

<tess_thm>
#thm[
  Let $P = P^n$ be a simple convex polytope in $XX^n$, where $n gt.eq 2$. Let ${F_i}_(i in I)$ be the collection of codimension-$1$ faces of $P^n$, with each face $F_i$ supported by the hyperplane $cal(H)_i$. Suppose for all $i eq.not j$, if $F_i sect F_j eq.not emptyset$ then the dihedral angle between $F_i$ and $F_j$ is $pi/(m_(i j))$ for some integer $m_(i j) gt.eq 2$. Put $m_(i i) = 1$ for every $i in I$, and $m_(i j) = infty$ if $F_i sect F_j = emptyset$. For each $i in I$, let $s_i$ be the isometric reflection of $XX^n$ across the hyperplane $cal(H)_i$. Let $W$ be the group generated by the set of reflections ${s_i}_(i in I)$. Then
  1. the group $W$ has presentation $
    W
      &= ang(s_i | (s_i s_j)^(m_(i j)) = 1 forall i, j in I);
  $
  2. the group $W$ is a discrete subgroup of $"Isom"(XX^n)$;
  3. the convex polytope $P$ is a strict fundamental domain for the action of $W$ on $XX^n$, and the action of $W$ induces a tessellation of $XX^n$ by copies of $P$.
][]

#defn(name: [Geometric reflection Group])[
  A group $W$ is a geometric reflection group if $W$ is either a finite dihedral group, an infinite dihedral group, or is as in the statement of the previous #link(<tess_thm>)[theorem]. A geometric reflection group $W$ acting on $XX^n$ is spherical, Euclidean or hyperbolic as $XX^n$ is, respectively, $SS^n, EE^n, HH^n$.
]

#ex(name: [Triangle groups])[
  For a tuple of integers $(p, q, r)$, where $2 lt.eq p lt.eq q lt.eq r$, there exists a triangle with interior angles $pi/p, pi/q, pi/r$. Note this triangle can exist in spherical, Euclidean, or hyperbolic space as its sum is respectively greater than, equal to, or less than $pi$. Note $
    W(p, q, r)
      &= ang(s_1, s_2, s_3 | s_1^2 = s_2^2 = s_3^2 = (s_1 s_2)^p = (s_2 s_3)^q = (s_3 s_1)^r = 1).
  $
]

== Definition of a Coxeter Group

#defn(name: [Coxeter System])[
  Let $I$ be a finite indexing set and let $S = {s_i}_(i in I)$. Let $M = (m_(i j)_(i, j in I)$ be a matrix such that:
  - $m_(i i) = 1$ for all $i in I$;
  - $m_(i j) = m_(j i)$ for all $i, j in I$;
  - $m_(i j) in {2, 3, 4, ...} union {infty}$ for all distinct $i, j in I$.
  Then $M$ is a Coxeter matrix. The associated Coxeter group $W = W_M$ is defined by the presentation $
    W
      &= ang(S | (s_i s_j)^(m_(i j)) = 1, forall i, j in I).
  $ The pair $(W, S)$ is a Coxeter system and the set $S$ is a Coxeter generating set for $W$.
]

#rem[
  Coxeter groups may have multiple distinct generating sets such that a Coxeter group's presentation is not unique.
]

#rem[
  Some definitions allows for Coxeter Systems $(W, S)$ in which $S$ is an infinite generating set.
]

== Right-angled Coxeter groups

#defn(name: [Right-angled Coxeter System])[
  Let $(W, S)$ be a Coxeter System with associated Coxeter matrix $M = (m_(i j))_(i, j in I)$. $(W, S)$ is right-angled, and $W$ is a right-angled Coxeter group if, for all distinct $i, j in I$, we have $m_(i j) in {2, infty}$.
]

#rem[
  Note that if $m_(i j) = 2$ then $s_i s_j = s_j s_i$.
]

#ex(name: [Coxeter Group, Not Geometric Reflection Group])[
  Consider the following group $
    W
      &= ang(s, t, u | s^2 = t^2 = u^2 = (s t)^2 = 1)
      &approx (C_2 times C_2) * C_2.
  $ Note $W$ is not a geometric reflection group.
]

== Weyl groups

#defn(name: [Root System])[
  A finite collection $Phi$ of vectors in $RR^n$ satisfying that $Phi$ spans $RR^n$ and $alpha in Phi$ then $RR alpha sect Phi = {alpha, - alpha}$. For each $alpha in Phi$, let $cal(H)_alpha = cal(H)_(-alpha)$ be the hyperplane through the origin which is orthogonal to $alpha$, and let $s_alpha = s_(-alpha)$ be the isometric reflection in $cal(H)_alpha$. Then $s_alpha$ swaps $alpha$ and $-alpha$, and the axioms for $Phi$ ensure that $s_alpha (beta)$ is in $Phi$ for all $beta in Phi$, and that all compositions of reflections $s_alpha s_beta$ have finite order. It is also required (only for crystallographic restrction) that for any $alpha, beta in Phi$ the projection of $beta$ onto $alpha$ must be an integer or half-integer multiple of $alpha$.
]

#defn(name: [Weyl Group])[
  The Weyl Group of a root system $Phi$ is the group $W = W(Phi)$ generated by the set of reflections ${s_alpha | alpha in Phi}$. It can be proved that $W$ is a finite Coxeter group, with Coxeter generating set given by a subset of the reflections ${s_alpha | alpha in Phi}$.
]

#ex(name: [Weyl Group $A_2$])[
  Let $Phi = {pm alpha, pm beta, pm (alpha + beta)}$ such that $W = W(Phi)$ is generated by $s_alpha, s_beta$ since $
    s_(alpha + beta) = s_alpha s_beta s_alpha = s_beta s_alpha s_beta.
  $
]

#rem[
  $D_(2 m)$ is a Weyl group if and only if $m in {2, 3, 4, 6}$.
]

#defn(name: [Crystallographic Restriction (Coxeter Matrix)])[
  A Coxeter matrix $M = (m_(i j))$ satisfies the crystallographic restriction if $m_(i j) in {2, 3, 4, 6, infty}$ for $i eq.not j$. If the crystallographic restriction is satisfied for a Coxeter group then it is the Weyl group for some Kac-Moody group.
]

= Some combinatorial theory of Coxeter groups

#notation[
  In contrast to a group product such as $s_1 dots.h.c s_n$, a word in $S$ written as a finite sequence of elements of $S$, $(s_1, ..., s_n)$.
]

<word_metric>
#defn(name: [Word Length])[
  The word length of some $g in G$ with respect to the generating set $S$ is $
    ell_S (g)
      &= min {n in NN | exists s_1, ..., s_n in S "such that" g = s_1 dots.h.c s_n}
  $ and $ell_S (1) = 0$. If $ell_S (g) = n gt.eq 1$ and $g = s_1 dots.h.c s_n$ then $(s_1, ..., s_n)$ is variously called a reduced expression, reduced word, or a minimal word for $g$. The word metric on $G$ with respect to $S$ is given by $
    d_S (g, h)
      &= ell_S (g^(-1) h).
  $
  #rem[
    Note that $d_S (h g, h g') = d_S (g, g')$.
  ]
]

#defn(name: [Cayley Graph])[
  A Cayley graph $Cay(G, S)$ has vertex set $G$ and edges given by ${(g, g s) | g in G, s in S}$. Note since $S$ is a generating set the graph is connected.

  #rem[
    $G$ acts on $Cay(G, S)$ on the left by graph automorphisms, preserving edge labels. Also note that $g s g^(-1)$ is the unique group element that flips the edge ${g, g s}$ since $s in S$ is an involution.
  ]

  #rem[
    The #link(<word_metric>)[word metric] extends directly to the path metric; the distance between two vertices on $Cay(G, S)$ where each edge is a unit length. This equivalence is found by observing $d_S (g, h) = ell_S (g^(-1) h)$ is trivially the shortest path from $e -> g^(-1) h$. Now if $g$ acts on $Cay(G, S)$ on the left we have that this same path is now from $g -> h$. As a graph automorphisms we have that this is the shortest path.
  ]
]

#lem[
  There is an epimorphism $epsilon: W -> ZZ_2$ induced by $epsilon(s) = 1$ for all $s in S$.
][]

<generators_involution>
#cor[
  Each $s in S$ is an involution in the group $W$.
][]

#lem[
  If $(W, S)$ is even, then for each $i in I$, there is an epimorphism $epsilon_i : W -> ZZ_2$ induced by $epsilon(s_i) = 1$ and $epsilon(s) = 0$ for all $s in S \\ {s_i}$.
][]

#cor[
  If $(W, S)$ is an even Coxeter system, the elements of $S$ are pairwise distinct group elements in $W$.
][]

<distinct_involution>
#cor[
  In a Coxeter system $(W, S)$, the elements of $S$ are pairwise distinct involutions in $W$.
][]

#defn(name: [Simple Graph])[
  Every edge must have distinct end points (no self-loops) and there should only exist at most one edge between an two distinct vertices.
]

<coxeter_simple_graph>
#cor[
  Let $(W, S)$ be a Coxeter system. Then $Cay(W, S)$ is a connected simple graph.
][
  Note by #link(<generators_involution>)[previous corollary] we have that $1 in.not S$ since $1$ is not an involution and therefore no self-loops can exist in $Cay(W, S)$. Also note by another #link(<distinct_involution>)[previous corollary] that all elements in $S$ are pairwise dinstinct group elements/involutions and therefore at most one edge may exist between two vertices. Therefore $Cay(W, S)$ is simple.
]

#defn(name: [Pre-Reflection System])[
  Let $X$ be a connected simple graph that $G$ acts on by graph automorphisms and let $R subset.eq G$ such that
  1. each $r in R$ is an involution;
  2. $R$ is closed under conjugation, that is, for all $g in G$ and all $r in R$, we have $g r g^(-1) in R$;
  3. $R$ generates $G$;
  4. for every edge $e$ in $X$ there exists a unique $r_e in R$ which flips $e$, that is, $r_e$ swaps the two end points of $e$;
  5. for every $r in R$ there is at least one edge $e$ in $X$ which is flipped by $r$.
  $(X, R)$ is a pre-reflection system for a group $G$ and for each $r in R$, the wall $H_r$ is the set of midpoints of edhes which are flipped by $r$.
]

#lem[
  Let $(W, S)$ be any Coxeter system. Let $X = Cay(W, S)$ and let $
    R
      &= {w s w^(-1) | w in W, s in S}.
  $ Then $(X, R)$ is a pre-reflection system.
][
  By the #link(<coxeter_simple_graph>)[previous corollary] we have that $Cay(W, S)$ is a connected simple graph. Note that $w s w^(-1)$ flips ${w, w s}$ and no other group element flips this edge.
]

#defn(name: [Reflection System])[
  A pre-reflection system $(X, R)$ is a reflection system if in addition for every $r in R$ we have that $X \\ H_r$ has exactly two components. Then $R$ is the set of reflections.
]

#defn(name: [Deletion Condition])[
  If $(s_1, ..., s_k)$ is a word in $S$ with $ell(s_1 dots.h.c s_k) < k$, then there are indices $i < j$ such that $
    s_1 dots.h.c s_k
      &= s_1 dots.h.c hat(s_i) dots.h.c hat(s_j) dots.h.c s_k
  $ where $hat(s_i)$ means we delete this letter.
]

#defn(name: [Exchange Condition])[
  If $(s_1, ..., s_k)$ is a reduced expression for $w in W$, the for any $s in S$, either $ell(s w) = k + 1$, or there is an index $i$ such that $
    w
      &= s s_1 dots.h.c hat(s_i) dots.h.c s_k.
  $
]

#thm[
  Suppose a group $W$ is generated by a set of distinct involutions $S$. Then the following are equivalent:
  1. The pair $(W, S)$ is a Coxeter system.
  2. If $X = Cay(W, S)$ and $R = {w s w^(-1) | w in W, s in S}$, then $(X, R)$ is a reflection system.
  3. The pair $(W, S)$ satisfies the deletion condition.
  4. The pair $(W, S)$ satisfies the exchange condition.
][]

<nondistinct_flips>
#lem[
  Suppose a group $W$ is generated by a set of distinct involutions $S$. Let $X = Cay(W, S)$ and let $R = {w s w^(-1) | w in W, s in S}$. Let $(s_1, ..., s_k)$ be a word in $S$ with associated sequence $(r_1, ..., r_k)$ of elements of $R$. If $r_i = r_j$ for some $1 lt.eq i < j lt.eq k$, then in the group $W$, $
    s_1 dots.h.c s_k
      &= s_1 dots.h.c hat(s_i) dots.h.c hat(s_j) dots.h.c s_k.
  $
][
  Let $r = r_i = r_j$ and for $1 lt.eq p lt.eq k$ let $w_p = s_1 dots.h.c s_p$. Let $gamma$ be the associated path in $X$, so $gamma$ has successive vertices $1, w_1, ..., w_k$. Now apply $r$ to the subpath of $gamma$ from $w_i -> w_(j - 1)$. The image is the path from $w_(i - 1) -> w_j$. The new path generated is given by $
    (s_1, ..., s_(i - 1), s_(i + 1), ..., s_(j - 1), s_(j + 1), ..., s_k).
  $
]

#lem[
  With the same assumptions as in the #link(<nondistinct_flips>)[previous lemma] for each $r in R$ we have that $X \\ H_r$ has at most two connected components.
][]

#lem[
  Assume that $(W, S)$ is a coxeter system. Then for all $w in W$ and $r in R$, any word for $w$ crosses $H_r$ the same number of times $mod 2$.
][]

#cor[
  Let $(W, S)$ be a Coxeter system, let $X = Cay(W, S)$ and let $
    R
      &= {w s w^(-1) | w in W, s in S}.
  $ Then $(X, R)$ is a reflection system.
][]

#cor[
  If $underline(s) = (s_1, ..., s_k)$ is a word in $S$ with associated reflections $(r_1, ..., r_k)$, then $underline(s)$ is a reduced expression if and only if $r_i$ are pairwise distinct.
][]

#defn(name: [Braid Move])[
  Let $s, t in S$ be distinct involutions and let $m_(s t)$ is the order of $s t$ in $W$. If $m_(s t)$ is finite, a braid move on a word in $S$ swaps a subword $(s, t, s, ...)$ containing $m_(s t)$ letters with a subword $(t, s, t, ...)$ containing $m_(s t)$ letters.
]

#thm(name: [Tits])[
  Suppose a group $W$ is generated by a set of distinct involutions $S$ and the exchange condition holds. Then
  1. a word $(s_1, ..., s_k)$ in $S$ is reduced if and only if it cannot be shortened by a sequence of
    - deleting a subword $(s, s), s in S$, or
    - carrying out a braid move;
  2. two reduced expressions in $S$ represent the same group element $w in W$ if and only if they are related by a finite sequence of braid moves.
][]

#ex(name: [Pre-Reflection System])[
  $D_infty times.r ZZ_2$
]

#rem[
  $B_3 = ang(a, b | a b a = b a b)$ is torsion free.
]

= The Tits representation

#thm(name: [Tits Representation])[
  Let $I$ be a finite indexing set, let $S = {s_i}_(i in I)$ and let $M = {m_(i j)}_(i, j in I)$ be a Coxeter matrix. Let $
    W
      &= ang(S | (s_i s_j)^(m_(i j)) = 1, forall i, j in I)
  $ be the associated Coxeter group. Then there is a faithful representation $
    rho: W -> GL_n (RR),
  $ where $n = |S| = |I|$, such that:
  - for each $i in I, rho(s_i) = sigma_i$ is a linear involution with fixed set a hyperplane;
  - for all $i eq.not j$, the product $sigma_i sigma_j$ has order $m_(i j)$.
][]

#ex(name: [Tits Representation])[
  Let $I = {1, ..., n}$ and let ${e_1, ..., e_n}$ be a basis for $V$, an $n$-dimensional vector space over $RR$. Define the symmetric bilinear form $
    B(e_i, e_j)
      &= cases(
        - cos(pi/(m_(i j)))#h(1em) &m_(i j) < infty,
        -1 &m_(i j) = infty
      ).
  $ Note $B(e_i, e_i) = 1$ and $B(e_i, e_j) lt.eq 0$ if $i eq.not j$. Consider the following $
    H_i
      &= {v in V | B(e_i, v) = 0} \
    sigma_i (v)
      &= v - 2 B(e_i, v) e_i.
  $ Note $sigma_i$ swaps $e_i$ and $-e_i$, fixes $H_i$, $sigma_i^2 = id$, and that $sigma_i$ preserves the bilinear form $B$.
]

#prop[
  1. The product $sigma_i sigma_j$ has order $m_(i j)$ for all distinct $i, j in I$.
  2. The map $s_i |-> sigma_i$ extends to a homomorphism $rho: W -> GL(V)$.
][]

#cor[
  Let $(W, S)$ be a Coxeter system. Then the selements of $S$ are pairwise distinct involutions of $W$.
][]

#cor[
  Let $(W, S)$ be a Coxeter sustem with Coxeter matrix $M = (m_(i j))$. Then for all distinct $i, j in I$, the product $s_i s_j$ has order $m_(i j)$ in $W$.
][]

#prop[
  $rho$ is faithful.
][]

#defn(name: [Chamber of Tits Representation])[
  The chamber $C$ associated to the Tits representation is a the subset of $V^*$ given by $
    C
      &= {phi in V^* | phi(e_i) gt.eq 0, forall i in I}.
  $ This chamber is the "simplicial cone" cut out by the hyperplanes $H_i^*$.

  We define the iterior of $C$ as $
    circle(C)
      &= "interior"(C)
      &= {phi in V^* | phi(e_i) > 0, forall i in I}.
  $
]

#thm[
  Let $w in W$, If $w circle(C)$. If $w circle(C) sect circle(C) eq.not emptyset$, then $w = 1$.
][]

#defn(name: [Tits Cone])[
  The Tits cone of $W$ is the subset of $V^*$ given by $union.big_(w in W) w C$.
]

#cor[
  A Coxeter group $W$ may be identified with a discrete subgroup of $GL_n (RR)$.
][]

#cor[
  Coxeter groups and their subgroups are linear.
][]

#thm(name: [Selberg's Lemma])[
  Finitely generated linear groups are virtually torsion-free.
][]

#thm(name: [Malcev's Theorem])[
  Finitely generated linear groups are residually finite.
][]

#cor[
  Coxeter groups are virtually torsion-free and residually finite.
][]

#defn(name: [Reducible/Irreducible])[
  A Coxeter system $(W, S)$ is reducible if $S = S' union.sq S''$ with $S'$ and $S''$ nonempty, such that $m_(i j) = 2$ for all $s_i in S'$ and $s_j in S''$. A Coxeter system $(W, S)$ is irreducible if it is not reducible.

  #rem[
    A reducible Coxeter group $W = ang(S') times ang(S'')$ is a clear direct product of generated groups.
  ]
]

#thm[
  Suppose $(W, S)$ is irreducible and $n = |S|$. Then we have:
  1. The bilinear form $B$ is positive definite if and only if $W$ is finite. In this case, $W$ is a spherical geometric reflection group generated by the set $S = {s_i}$ of reflections in the codimension-$1$ faces of a simplex in $SS^(n - 1)$, with $s_i$ the reflection in face $F_i$, so that faces $F_i$ and $F_j$ meet at dihedral angle $pi/(m_(i j))$.
  2. The bilinear form $B$ is positive semidefinite of corank $1$ if and only if $W$ is a Euclidean geometric reflection group. In this case, $W$ is generated by the set $S = {s_i}$ of reflections in the codimension-$1$ faces of either
    - if $n = 2$, an interval in $EE^1$ (this is the case $W = D_infty$);
    - if $n > 3$, a simplex in $EE^(n - 1)$, with $s_i$ the reflection in the codimension-$1$ face $F_i$, so that faces $F_i$ and $F_j$ meet at dihedral angle $pi/(m_(i j))$.
][]

#defn(name: [Coxeter Polytope])[
  Let $W$ be a finite Coxeter group. A Coxeter polytope for $W$ is the convex hull of the $W$-orbit on $V^*$ of a point $x in circle(C)$.
]

#defn(name: [Special Subgroup])[
  For each $T subset.eq S$, the special subgroup $W_T$ of $W$ is $W_T = ang(T)$. If $T = emptyset$, we define $W_emptyset$ to be the trivial group. Note these subgroups are also called (standard) parabolic subgroups or visual subgroups.
]

#notation[
  If $J subset.eq I$ then $W_J = ang(s_j | j in J)$.
]

#thm[
  Let $(W, S)$ be a Coxeter system.
  1. The pair $(W_T, T)$ is a Coxeter system for each $T subset.eq S$.
  2. For all $T subset.eq S$ and $w in W_T$, we have $ell_T (w) = ell_S (w)$, and any reduced expression for $w$ uses only letters in $T$. Hence $Cay(W_T, T)$ embeds isometrically as a convex subgraph of $Cay(W, S)$.
  3. If $T, T' subset.eq S$, then $W_T sect W_(T') = W_(T sect T')$ and $ang(W_T, W_(T')) = W_(T union T')$.
  4. The map $T |-> W_T$ is a bijection $
    {"subsets of" S} --> {"special subgroups of" W}
  $ which preserves the partial order given by inclusion.
][]

= The basic construction of a geometric realisation

#defn(name: [Abstract Simplicial Complex])[
  An abstract simplicial complex consists of a set $V$, possibly infinite, called the vertex set, and a collection $X$ of finite subsets of $V$, such that
  1. ${v} in X$ for all $v in V$;
  2. if $Delta in X$ and $Delta' subset.eq Delta$, then $Delta' in X$.

  An element of $X$ is called a simplex. If $Delta$ is a simplex and $Delta' subset.neq Delta$ then $Delta'$ is a face of $Delta$.

  $Delta$ is a $k$-simplex if $dim Delta = |Delta| - 1 = k$.

  The $k$-skeleton $X^((k))$ is the union of all simpleces of dimension at most $k$ (note this is a simplicial complex).

  The dimension of a simplicial complex $X$ is $dim X = max{dim(Delta) | Delta in X}$.

  $X$ is pure if all its maximal simplicies have the same definition.

  #ex(name: [Standard $n$-simplex $Delta^n$])[
    The standard $n$-simplex, $Delta^n$, is the convex hull of $(n + 1)$ points $(1, ...), ..., (0, ..., 1) in RR^(n + 1)$.
  ]

  #rem[
    If $X$ is a simplicial cell complex and $Delta subset.eq X^((0))$ then $Delta in X$ if and only if $Delta$ spans a copy of $Delta^n$ in $X$.
  ]
]

#defn(name: [Mirror Structure])[
  Let $(W, S)$ be any Coxeter system and let $X$ be a connected, Hausdorff topological space. A mirror structure on $X$ over $S$ is a collection $(X_s)_(s in S)$ where each $X_s$ is a nonempty, closed subset of $X$. For each $s in S$, we call $X_s$ the $s$-mirror of $X$.
]

#notation[
  Define $S(x) := {s in S | x in X_s}$.
]

#rem[
  We define a relation $sim$ on $W times X$ by $
    (w, x) sim (w', x') iff x = x' and w^(-1) w' in W_(S(x))
  $ where $W_T$ is the special subground $ang(T)$. Note $W$ is a Coxeter group and $X$ is some connect, Hausdorff, topological space.
]

#defn(name: [Basic Construction])[
  The basic construction is the quotient $
    cal(U) (W, X)
      &= W times X \/sim
  $ equipped with the quotient topology (where $W$ is equipped with the discrete topology). $[w, x]$ is the equvialence class of $(w, x) in cal(U) (W, X)$.

  $w X = {w} times X$ is called a chamber. Note there is an embedding $X -> w X, x |-> [w, x]$.
]

#lem[
  We have that $cal(U) (W, X)$ is a connected topological space.
][]

#defn(name: [Locally Finite])[
  We say $cal(U) (W, X)$ is locally finite if for every $[w, x] in cal(U) (W, X)$ there is an open neighborhood of $[w, x]$ which meets only finitely many chambers.
]

#lem[
  The following are equvialent
  1. The basic construction $cal(U) (W, X)$ is locally finite.
  2. For all $x in X$, the special subgroup $W_(S(x))$ is finite.
  3. For all $T subset.eq S$ such that $W_T$ is infinite, $sect.big_(x in T) X_t = emptyset$.
][]

#lem[
  The fundamental chamber $X$ is a strict fundamental domain for the action $W$ on $cal(U) (W, X)$. Hence $cal(U) (W, X) \/ W$ is the Hausdorff space $X$.
][]

#lem[
  The stabiliser in $W$ of $[w, x] in cal(U) (W, X)$ is $w W_(S(x)) w^(-1)$. In particular, up to conjugacy every point stabiliser subgroup of $W$.
][
  Consider the following $
    "Stab"_W ([w, x])
      &= {w' in W | w' dot (w, x) sim (w, x)} \
      &= {w' in W | (w' w, x) sim (w, x)} \
      &= {w' in W | (w' w)^(-1) w in W_(S(x))} \
      &= {w' in W | w^(-1) w' w in W_(S(x))} \
      &= w W_(S(x)) w^(-1).
  $
]

#lem[
  The space $cal(U) (W, X)$ is Hausdorff.
][]

#defn(name: [Properly Discontinuous])[
  Let $G$ be a discrete group and let $Y$ be a Hausdorff space. An action by homeomorphisms of $G$ on $Y$ is properly discontinuous if
  1. the quotient $Y \/ G$ is Hausdorff;
  2. for all $y in Y$, the group $G_u = "Stab"_G (y)$ is finite;
  3. for all $y in Y$, there is an open neighborhood $U_y$ of $y$ which is stabilised by $G_y$ such that $g U_y sect U_y = emptyset$ for all $g in G \\ G_y$.
]

#lem[
  The $W$-action on $cal(U) (W, X)$ is properly discontinuous if and only if $W_(S(x))$ is finite for every $x in X$.
][]

#thm(name: [Vinberg])[
  Let $(W, S)$ be any Coxeter system. Suppose $W$ acts by homeomorphisms on a connected Hausdorff space $Y$ such that every $s in S$, the fixed point set $Y^s$ of $s$ is nonempty. Suppose further that $X$ is a connected Hausdorff space iwth mirror structure $(X_s)_(s in S)$. Then if $f:X -> Y$ is a continuous map such that $f(X_s) subset.eq Y^s$ for all $s in S$, there is a unique extension of $f$ to a $W$-equivariant map $tilde(f) : cal(U) (W, X) -> Y$ given by $
    tilde(f) ([w, x])
      &= w dot f(x).
  $
][]

#thm[
  Let $X = P^n$ be a simple convex polytope in $XX^n$ for $n gt.eq 2$, with codimension-$1$ faces ${F_i}_(i in I)$. Assume that if $i eq.not j$ and $F_i sect F_j eq.not emptyset$, then the dihedral angle between $F_i$ and $F_j$ is $pi/(m_(i j))$ where $m_(i j) in {2, 3, ...}$ is finite. Put $m_(i i) = 1$ and $m_(i j) = infty$ if $F_i sect F_j = emptyset$.

  Let $S = {s_i}_(i in I)$ and let $(W, S)$ be the Coxeter system with Coxeter matrix $(m_(i j))_(i, j in I)$. Define a mirror structure on $X$ by $X_(s_i) = F_i$. For each $i in I$, let $overline(s)_i in "Isom"(XX^n)$ be the reflection in $F_i$. Let $overline(W)$ be the subgroup of $"Isom"(XX^n)$ generated by the set $overline(s)_i$. Then
  1. there is an isomorphism $phi: W -> overline(W)$ induced by $s_i |-> overline(s)_i$;
  2. the induced map $cal(U) (W, P^n) -> XX^n$ is a homeomorphism;
  3. the Coxeter group $W$ acts properly discontinuously on $XX^n$ with strict fundamental domain $P^n$, hence $W$ is a discrete subgroup of $"Isom"(XX^n)$ and $XX^n$ is tessellated by copies of $P^n$.
][]

#defn(name: [Atlas])[
  A $n$-dimensional topological manifold $M^n$ has an $XX^n$-strcture if it has an atlas of charts ${psi_alpha : U_alpha -> XX^n}_(alpha in A)$ such that
  - $(U_alpha)_(alpha in A)$ is an open cover of $M^n$;
  - each $psi_alpha$ is a homeomorphism onto its image;
  - for all $alpha, beta in A$ the map $
    psi_beta comp psi^(-1)_alpha : psi_alpha (U_alpha sect U_beta) -> psi_beta (U_alpha sect U_beta)
  $ is the restriction of an element of $"Isom"(XX^n)$.

  In particular an $XX^n$-structure turns $M^n$ into a smooth Riemannian manifold. We will use the following
  - An $XX^n$-structure on $M^n$ induces one on its universal cover $tilde(M)^n$.
  - There is a developing map $D : tilde(M)^n -> XX^n$ given by analytic continuation along paths.
  - If $M^n$ is metrically complete, $D$ is a covering map.
]

= The Davis complex

#notation[
  The Davis complex generated by the Coxeter system $(W, S)$ is denoted by $Sigma = Sigma(W, S)$.
]

#defn(name: [Spherical Subsets and Spherical Special Subgroup])[
  A subset $T subset.eq S$ is a *spherical* if the special subgroup $W_T$ is finite, in which case we say that $W_T$ is a *sphecial special subgroup* (this is due to $W_T$ acting naturally on a sphere if it is irreducible).
]

#rem[
  Finite irreducible Coxeter systems are classified.
]

#defn(name: [Nerve])[
  The nerve of $(W, S)$, denoted $L = L(W, S)$, is the simplicial complex with a simplex $sigma_T$ for each $T subset.eq S$ such that $T eq.not emptyset$ and $W_T$ is finite.

  Note this is a simplicial complex (although it encludes the empty simplex).
]

#ex(name: [Nerve of Triangle Group])[
  If $W$ is the $(3, 3, 3)$-triangle group we have $
    W
      &= ang(s, t, u | s^2 = t^2 = u^2 = (s t)^3 = (t u)^3 = (u s)^3 = 1).
  $ Then the nerve $L$ is a triangle with vertices $s, t, u$ with no interior since $W$ is infinite.
]

#rem[
  Fora given Euclidean or hyperbolic geometric reflection group $W$ with strict fundamental domain $P$ the nerve $L$ can be identified with the boundary of $P^*$ (the dual polytope of $P$).
]

#ex(name: [Right-angled Defining Graph])[
  Let $Gamma$ be a finite simple graph with vertex set $S = V(Gamma)$ and edge set $E(Gamma)$. Then we have $
    W_Gamma
      &= ang(S | s^2 = 1, forall s in S, s t = t s <==> {s, t} in E(Gamma)) \
      &= ang(S | s^2 = 1, forall s in S, (s t)^2 = 1 <==> {s, t} in E(Gamma))
  $ is the associated right-angled Coxeter group. $Gamma$ is called the defining graph of $W_Gamma$.

  Note that if $S$ has no spherical subsets $T$ with $|T| > 2$ then $L(W_Gamma, S) = Gamma$.
]

#defn(name: [Flag Complex])[
  A simplicial complex $L$ is a flag complex if a finite nonempty set of vertices $T$ in $L$ spans a simplex in $L$ if and only if any two elements of $T$ span an edge in $L$.
]

#lem[
  If $(W, S)$ is a right-angled Coxeter system, then $L(W, S)$ is a flag complex.
][
  Suppose $T subset.eq S, T eq.not emptyset$ and any two vertices in $T$ are connected by an edge in $L$. Then $W_T approx (C_2)^(|T|)$ is finite, so $T$ is spherical and $sigma_T$ is in $L$.
]

#defn(name: [Chamber of Davis Complex])[
  The chamber $K$ is the cone on the barycentric subdivision $L'$ of the nerve $L = L(W, S)$. For each $s in S$, define $K_s subset K$ to be the closed star in $L'$ of the vertext $s$.
]

#lem[
  For all $x in K$, the set $S(X) = {s in S | x in K_s}$ is spherical, so each $W_(S(x))$ is finite. Moreover, the collection ${S(x) | x in K}$ is exactly the collection of spherical subsets of $S$.
][]

#ex(name: [Chamber of Polytope])[
  Let $W$ be a Euclidean or hyperbolic geometric reflection group with fundamental domain $P$ and let $P^*$ be its dual polytope. Then $L = bound P^*$ such that $L' = (bound P^*)' = (bound P)'$. Thus $K$ is the cone on the barycentric subdivision of $bound P$. The mirrors are the barycentric subdivisions of the codimension-$1$ faces of $P$.
]

#defn(name: [Davis Complex (Basic Construction)])[
  The *Davis complex* $Sigma = Sigma(W, S)$ is the basic construction $
    Sigma
      &= cal(U)(W, K)
      &= W times K \/ sim,
  $ where the chamber $K$ with mirror structure $(K_s)_(s in S)$ is as before.
]

#cor[
  The Davis complex $Sigma = cal(U)(W, K)$ is connected, Hausdorff, and locally finite. The $W$-action on $Sigma$ is properly discontinuous with quotien $K$, and all point stabilisers are conjugates of finite special subgroups of $W$.
][]

#thm[
  The Davis complex $Sigma = Sigma(W, S)$ is contractible.
][]

#defn[
  For $w in W$ define $
    "In"(w)
      &= {s in S | ell(w s) < ell(w)} \
      &= {s in S | "a reduced expression for" w "can end in" s} \
    "Out"(w)
      &= {s in S | ell(w s) > ell(w)}.
  $ Since $ell(w s) = ell(w) pm 1$, we have $S = "In"(w) union.sq "Out"(w)$.
]

#prop[
  For all $w in W$, $"In"(w)$ is a spherical subset, that is, $W_("In"(w))$ is finite.
][]

#lem[
  Suppose there is a $w_0 in W$ such that $ell(w_0 s) < ell(w_0)$ for all $s in S$. Then $W$ is finite.
][]

#lem[
  Let $T subset.eq S$ and suppose $w$ is a minimal length element in the left coset $w W_T$. Then any $w' in w W_T$ can be written as $w' = w a'$ where $a' in W_T$ is such that $ell(w') = ell(w) + ell(a')$. Moreover, each coset $w W_T$ contains a unique element of minimal length.
][]

#lem[
  The chamber $K$ is contractible, and for all spherical $T subset.eq S$, the union of mirrors $
      K^T
        &= union.big_(t in T) K_t
    $ is contractible.
][]

#lem[
  The chamber $K$ defined previously is the geometric realisation of the post ${T subset.eq S | W_T "is finite"}$ order by inclusion.
][]

#cor[
  The chamber $K$ defined previously is the geometric realisation of the poset ${W_T | T subset.eq S "and" W_T "is finite"}$ ordered by inclusion.
][]

#thm[
  We can identify the Davis complex $Sigma$ with the geometric realisation of the poset $
    {w W_T | w in W, T subset.eq S "and" W_T "is finite"},
  $ ordered by inclusion.
][]

#thm[
  We can identify the (barycentric subdivision of the) Coxeter complex with the geometric realisation of the poset $
    {w W_T | w in W, T subset.neq S},
  $ ordered by inclusion.
][]

#thm[
  The Davis complex $Sigma$ may be identified with the CW complex which has $1$-skeleton $Cay(W, S)$, and a cell with vertex set $U subset.eq W$ whenever $U = w W_T$ for some $w in W$ and $T subset.eq S$ with $W_T$ finite.
][]

#lem[
  The Davis complex $Sigma$ is simply connect.
][]

#defn(name: [Polyhedral Complex])[
  A *polyhedral complex* is a finite-dimensional CW complex in which each $n$-cell is metrised as convex polytope in $XX^n$ (the same $XX$ for each cell), and the restrictions of the attaching maps to codimension-$1$ faces are isometries. A polyhedral complex is spherical, Euclidean or hyperbolic as $XX^n$ is $SS^n$, $EE^n$, or $HH^n$, respectively.
]

#defn(name: [Geodesic Space])[
  For $x, y in X$ a geodesic from $x$ to $y$ is a map $gamma$ from $[a, b] subset.eq RR$ to $X$ so that $gamma(a) = x, gamma(b) = y$ and $d(gamma(t), gamma(t')) = |t - t'|$ for all $i, t' in [a, b]$. $(X, d)$ is a geodesic space if every pair of points in $X$ is connected by a geodesic.
]

#thm[
  If a connected polyhedral complex $X$ has finitely many isometry types of cells, then $X$ is a complete geodesic space.
][]

#thm[
  When equipped with the piecewise Euclidean metric determined by $underline(d) = (d_s)_(s in S)$ as below, $Sigma = Sigma(underline(d))$ is a complete $"CAT"(0)$ space.

  $underline(d)$ is a sequence where $d_s > 0$. Let $rho_T : W_T -> O(|T|, RR)$ for any finite $W_T$ where $rho_T (t)$ is the hyperplane $H_t$ with unit normal vector $e_t$. $H_t$ and $H_(t')$ meet at dihedral angle $pi/m$ where $ang(t, t') approx D_(2 m)$. Let the chamber $
    C_T
      &= {x in RR^n | ang(x, e_t) gt.eq 0, forall t in T}.
  $ There exists a unique point $x_T = x_T(underline(d))$ in the interior of $C_T$ such that $d(x_T, H_t) = d_t > 0$ for all $t in T$. Each cell is metrised with vertex set $w W_T$.
][]

#defn(name: [Comparison Triangle])[
  Let $[x y]$ be the geodesic segment from $x$ to $y$ is the geodesic space $(X, d)$. Given a geodesic triangle $
    Delta
      &= [x_1 x_2] union [x_2 x_3] union [x_3 x_1]
  $ in $X$, there is a comparison triangle $
    overline(Delta)
      &= [overline(x)_1 overline(x)_2] union [overline(x)_2 overline(x)_3] union [overline(x)_3 overline(x)_1]
  $ with $d_X (x_i, x_j) = d_(EE^2) (overline(x)_i overline(x)_j)$ for any $i eq.not j$. For any $p in [x_i x_j]$ there is a unique comparison point $overline(p) in [overline(x)_i overline(x)_j]$ such that $d_X (x_i p) = d_(EE^2) (overline(x)_i overline(p))$.
]

#defn(name: [$"CAT"(0)$])[
  A geodesic space $(X, d_X)$ is $"CAT"(0)$ if for every geodesic triangle $Delta$ in $X$, and all points $p, q in Delta$, $
    d_X (p, q)
      &lt.eq d_(EE^2) (overline(p), overline(q)).
  $

  Similarly a geodesic is $"CAT"(-1)$ if $
    d_X (p, q)
      &lt.eq d_(HH^2) (overline(p), overline(q))
  $ or $"CAT"(1)$ if $
    d_X (p, q)
      &lt.eq d_(SS^2) (overline(p), overline(q)).
  $
]

#thm[
  Let $X$ be a complete $"CAT"(0)$ space. Then we have the following properties:
  1. The space $X$ is uniquely geodesic.
  2. The space $X$ is contractible.
  3. Suppose a group $G$ acts on $X$ by isometries. Let $H$ be a subgroup of $G$ and write $X^H$ for the fixed set of $H$ in $X$. If $X^H$ is nonempty then $X^H$ is convex. In particular, since closed, convex subsets of complete $"CAT"(0)$ spaces are complete $"CAT"(0)$ spaces, every nonempty fixed set $X^H$ is contractible by (2).
  4. (Bruhat-Tits fixed point theorem). If a group $G$ acts on $X$ by isometries and $G$ has a bounded orbit, then $X^G eq.not emptyset$. In particular, for every finite subgroup $H lt.eq G$, we have $X^H eq.not emptyset$, and so $X^H$ is contractible by (3).
  5. If a group $G$ acts properly discontinuously and cocompactly by isometries on $X$ then the word problem and the conjugacy problem are both solvable for $G$.
][]

#cor[
  Let $(W, S)$ be a Coxeter system and $Sigma = Sigma(W, S)$ be the associated Davis complex, equipped with a $"CAT"(0)$ metric.
  1. The complex $Sigma$ is contractible.
  2. If $H lt.eq W$ is finite, then $Sigma^H$ is nonempty and contractible, and there is an element $w in W$ and a spherical subset $T subset.eq S$ such that $H lt.eq w W_T w^(-1)$.
  3. The word and conjugacy problems for $W$ are solvable.
][]

#thm(name: [Cartan-Hadamard theorem for $"CAT"(0)$ spaces])[
  Let $X$ be a complete, connected geodesic metric space. If $X$ is locally $"CAT"(0)$ then the universal cover of $X$ is $"CAT"(0)$.
][]

#thm(name: [Gromov link condition])[
  If $X$ is a piecewise Euclidean polyhedral complex then $X$ is locally $"CAT"(0)$ if and only if for every vertex $v$ of $X$, the link of $v$ in $X$ is $"CAT"(1)$.
][]

#lem[
  In $Sigma$, the link of the vertex $v = 1$ is $L$, with each simplex $sigma_T$ of $L$ metrised as the simplex $Delta_T$ in $SS^(|T| - 1)$ with the vertex set ${e_t}_(t in T)$ ($L$ is a nerve).
][]

#thm[
  Suppose all simplices of a simplicial complex $Delta$ are metrised as right-angled spherical simplices. Then $Delta$ is $"CAT"(1)$ if and only if $Delta$ is flag.
][]

#defn(name: [Cube Complex])[
  A *cube complex* is a Euclidean polyhedral complex in which each cell is metrised as Euclidean cube.
]

#cor[
  If $W_Gamma$ is right-angled, $Sigma = Sigma_Gamma$ can be metrised as a $"CAT"(0)$ cube complex.
][]

#thm[
  Suppose a simplicial complex $Delta$ is metrised as a spherical simplicial complex in which all edge lengths are $gt.eq pi/2$. Then $Delta$ is $"CAT"(1)$ if and only if $Delta$ is a metric flag complex.
][]

<Moussong>
#thm[
  There exists a piecewise hyperbolic structure on $Sigma$ which is $"CAT"(-1)$ if and only if there is no subset $T subset.eq S$ such that either
  1. $W_T$ is an Euclidean geometric reflection group of dimension $gt.eq 2$; or
  2. $(W_T, T)$ is reducible with $W_T = W_(T') times W_(T'')$ and $W_(T')$ and $W_(T'')$ both infinite.
][]

#defn(name: [Word Hyperbolic])[
  $W$ is word hyperbolic if there exists $delta > 0$ so that every geodesic triangle $Delta$ in $Cay(W, S)$ is $delta$-thin, meaning that the $delta$-neighborhood of any two sides of $Delta$ contains the third. Word hyperbolic groups are sometimes also called Gromov hyperbolic groups.
]

#thm[
  Let $(W, S)$ be a Coxeter system. If $W$ is word hyperbolic then
  1. $W$ has no $ZZ times ZZ$ subgroup;
  2. $W$ has a solvable word and conjugacy problem;
  3. $W$ satisfies a linear "isoperimetric inequaility"; and
  4. $W$ is automatic and biautomatic.
][]

#cor[
  If $W = W_Gamma$ is right-angled then $W_Gamma$ is word hyperbolic if and only if $Gamma$ has no empty squares.
][]

#cor[
  Let $(W, S)$ be a Coxeter system. The following are equivalent:
  1. The group $W$ is word hyperbolic.
  2. The group $W$ has no $ZZ times ZZ$ subgroup.
  3. There is no subset $T subset.eq S$ such that (1) and (2) in #link(<Moussong>)[previous theorem] holds.
  4. The complex $Sigma$ admits a piecewise hyperbolic metric which is $"CAT"(-1)$.
][]

#defn(name: [Classifying Space])[
  A *classifying space* for a group $G$, denoted $B G$, is an aspherical CW complex with fundamental group $G$. It is also called an *Eilenberg-MacLane space* or a $K(G, 1)$. The universal cover of $B G$, denoted $E G$, is called a *universal space* for $G$.
]

#thm[
  Let $(W, S)$ be a Coxeter system with nerve $L$, chamber $K$ and Davis complex $Sigma$. Then $
    H^i (W; ZZ W)
      &iso H_c^i (Sigma) \
      &iso plus.big_(w in W) H^i (K, K^("Out"(w))) \
      &iso plus.big {(ZZ W^T times.circle H^i (K, K^(S - T)) | T subset.eq S, T "is spherical"}\
      &iso plus.big {(ZZ W^T times.circle overline(H^(i - 1)) (L - sigma_T) | T subset.eq S, T "is spherical"}.
  $
][]

#defn(name: [Universal Space])[
  Let $G$ be a discrete group. A CW complex $X$ together with a proper, cocompact, cellular $G$-action is a universal space for proper $G$-actions, denoted $underline(E) G$, if for all finite subgroups $H$ of $G$, the fixed set $X^H$ is contractible.
]

#thm[
  For any discrete group $G$, an $underline(E) G$ exists and is unique up to $G$-homotopy, and $
    H^* (G;ZZ G)
      &= H_c^* (underline(E) G).
  $
][]

#prop[
  If a discrete group $G$ acts properly discontinuously and cocompactly on an acyclic CW complex $X$ then $
    H^* (G;ZZ G)
      &= H_c^* (X).
  $
][]

#cor[
  The Davis complex $Sigma = Sigma(W, S)$ is a finite-dimensional $underline(E) W$. Moreover, $W$ acts properly discontinuously and cocompactly on $Sigma$, and $Sigma$ is acyclic (since it is contractible).
][]

= Buildings as unions of apartments

#defn(name: [Building])[
  Let $(W, S)$ be a Coxeter system. A *building* of type $(W, S)$ is a simplicial complex $Delta$ which is a union of subcomplexes called *apartments*, with each apartment being a copy of the Coxeter complex for $(W, S)$. The maximal simplices in $Delta$ are called its *chambers*, and the following axioms hold:
  1. Any two chambers are contained ina common aparment.
  2. If $A$ and $A'$ are any two apartments, there is an isomorphism $A -> A'$ which fixes $A sect A'$ pointwise.
]

#rem[
  A building may be the union of more than one collection of subcomplexes.
]

#rem[
  Am generalised $m$-gon is the same thing as a building of type $D_(2 m)$. Where a generalised $m$-gon is a connected bipartite graph with girth $2 m$ (shortest circuit) and diameter $m$ (the maximal distance between two veritices).
]

= Buildings as chamber systems

#defn(name: [Chamber System])[
  Let $I$ be a finite set. A set $C$, whose elements are called chambers, is a chamber system over $I$ if each $i in I$ determines an equivalence relation on $C$, denoted $sim_i$. We say that chambers $x$ and $y$ are $i$-adjacent if $x sim_i y$, and that they are adjacent if $x sim_i y$ for some $i in I$.
]

#defn(name: [Gallery])[
  A sequence of chambers $gamma = (c_0, ..., c_k)$ is a chamber if $c_(j - 1)$ is adjacent to $c_j$ and $c_(j - 1) eq.not c_j$. $gamma$ is of type $(i_1, ..., i_k)$ where $c_(j - 1) sim_(i_j) c_j$.
]

#defn(name: [$J$-residue])[
  For any $J subset.eq I$ a $J$-residue is a $J$-connected component of $C$ that is a maximal subset of $C$ such that each pair of chambers in this subset is connected by a gallery with type  a tuple of indexes in $J$.

  Note that ${i}$-residue is an $i$-panel.
]

#defn(name: [$W$-valued distance function])[
  $W$-valued distance function is a map $
    delta: C times C -> W
  $ such that for all reduced words $(s_(i_1), ..., s_(i_k))$ and all $x, y in C$, the following holds: $delta(x, y) = s_(i_1) dots.h.c s_(i_k)$ if and only if there is a gallery from $x$ to $y$ in $C$ of type $(i_1, ..., i_k)$.
]

#defn(name: [Building])[
  Let $(W, S)$ be a Coxeter system with $S = {s_i | i in I}$. A building of type $(W, S)$ is a chamber system $Delta$ over $I$ which is equipped with a $W$-valued distance function, and is such that each panel has at least two chambers.

  A building is thick if each panel has at least three chambers, and thin if each panel has exactly two chambers.
]

#prop[
  Let $(W, S)$ be a Coxeter system and let $Delta$ be a building of type $(W, S)$, with $W$-valued distance function $delta: Delta times Delta -> W$. Then
  1. $Delta$ is connected;
  2. $delta$ maps onto $W$;
  3. for all $x, y in Delta$, we have $delta(x, y) = delta(y, x)^(-1)$;
  4. for all $x, y in Delta$, we have $delta(x, y) = s_i$ if and only if $x sim_i y$ and $x eq.not y$;
  5. if $x, y in Delta$ with $x eq.not y$, and $x sim_i y$ and $x sim_y y$, then $i = j$; and
  6. if $(s_(i_1), ..., s_(i_k))$ is reduced in $(W, S)$, then for all chambers $x$ and $y$ there is at most one gallery of type $(i_1, ..., i_k)$ from $x$ to $y$.
][]

#defn(name: [Minimal Gallery])[
  A gallery in $Delta$ is minimal if there is no shorter gallery between its end points.
]

#lem[
  A gallery of type $(i_1, ..., i_k)$ is minimal if and only if the word $(s_(i_1), ..., s_(i_k))$.
][]

#prop[
  If $J subset.eq I$, then every $J$-residue is a building of type $(W_J, J)$.
][]

#defn(name: [$W$-isometric embedding])[
  For any subset $X subset.eq W$, a map $alpha: X -> Delta$ is a $W$-isometric embedding if, for all $x, y in X$, $
    delta(alpha(x), alpha(y))
      &= x^(-1) y.
  $

  An apartment is any image of $W$ under a $W$-isometric embedding.
]

#prop[
  For any proper subset $X subset.neq W$, any $W$-isometric embedding $alpha: X -> Delta$ extends to a $W$-isometric embedding of $W$.
][]

#thm[
  Let $Delta$ be a building, so that its apartments are copies of some basic construction $cal(U) (W, X)$.
  1. If $Delta$ is a spherical building (its apartments are spheres tiled by the action of $W$) then $Delta$ is a $"CAT"(1)$ space.
  2. If $Delta$ is a Euclidean or affine building (its apartments are Euclidean spaces tiled by the action of $W$) then $Delta$ is a $"CAT"(0)$ space.
  3. If $Delta$ is a hyperbolic building (its apartments are hyperbolic spaces tiled by the action of $W$) then $Delta$ is a $"CAT"(-1)$ space.
  4. If the apartments of $Delta$ are Davis complexes, then $Delta$ can be equipped with a piecewise Euclidean metric such that it is a $"CAT"(0)$ space.
  5. If the apartments of $Delta$ are Davis complexes, and $W$ is word hyperbolic, then $Delta$ can be equipped with a piecewise hyperbolic metric such that it is a $"CAT"(-1)$ space.
][]

#defn(name: [Graph Product])[
  Let $Gamma$ be a finite simple graph with vertex set $S$ and edge set $E(Gamma)$. For each $s in S$, let $G_s$ be a nontrivial group. The graph product of the family ${G_s}_(s in S)$ over $Gamma$ is the group $G_Gamma$ which is the quotient of the free product of the groups $G_s$ by the normal subgroup generated by the commutators $
    {[g_s, g_t] : g_s in G_s, g_t in G_t "and" {s, t} in E(Gamma)}.
  $ That is, the graph $G_Gamma$ is generated by the vertex groups $G_s$, with $G_s$ and $G_t$ commuting in $G_Gamma$ if and only if $s$ and $t$ are adjacent vertices. Graph products of groups are sometimes called graph groups.
]

#thm(name: [Green])[
  If $g = g_(1_i) dots.h.c g_(i_k)$ and $g' = g'_(i_1) dots.h.c g'_(i_k)$ are reduced expressions for $g, g' in G_Gamma \\ {1}$, then $g = g'$ in the group $G_Gamma$ if and only if one can get from one expression to the other by "shuffling", that is, using relations of the form $[g_(i_j), g_(i_(j + 1))] = 1$.
][]
